# Generated by Django 6.0.5 on 2026-06-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='off_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='payroll_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
