# Generated by Django 6.0.5 on 2026-05-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrols', '0002_alter_shift_options_shift_end_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patrollog',
            options={'ordering': ['-scanned_at']},
        ),
        migrations.AddField(
            model_name='patrollog',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patrollog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patrollog',
            name='invalid_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
