# Generated by Django 6.0.5 on 2026-05-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrols', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='shift',
            name='end_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='end_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='start_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='start_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
