# Generated by Django 6.0.5 on 2026-05-10 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrols', '0003_alter_patrollog_options_patrollog_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patrollog',
            name='scanned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incident',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]