# Generated by Django 6.0.5 on 2026-05-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrols', '0004_alter_incident_created_at_alter_patrollog_scanned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='incidents/files/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='incidents/audio/'),
        ),
        migrations.AddField(
            model_name='incident',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='incidents/video/'),
        ),
    ]