# Generated by Django 6.0.5 on 2026-06-01 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organisation'),
        ('patrols', '0006_checkpoint_qr_defaults_patrollog_checkpoint_coords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='route',
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='patrols.site'),
        ),
        migrations.AddField(
            model_name='site',
            name='guards',
            field=models.ManyToManyField(blank=True, related_name='assigned_sites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='site',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='accounts.organisation'),
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
